// <auto-generated />
using System;
using ExecutionService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExecutionService.Migrations
{
    [DbContext(typeof(ExecutionServiceDbContext))]
    partial class ExecutionServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ExecutionService.Entities.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaymentPercentage")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weightage")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("ExecutionService.Entities.MilestoneDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MilestoneSubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MilestoneSubmissionId");

                    b.ToTable("MilestoneDocuments");
                });

            modelBuilder.Entity("ExecutionService.Entities.MilestoneSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsImmutable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkedReportIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MilestoneId");

                    b.ToTable("MilestoneSubmissions");
                });

            modelBuilder.Entity("ExecutionService.Entities.MilestoneTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MilestoneTemplates");
                });

            modelBuilder.Entity("ExecutionService.Entities.MilestoneTemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MilestoneTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentageReleasing")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MilestoneTemplateId");

                    b.ToTable("MilestoneTemplateItem");
                });

            modelBuilder.Entity("ExecutionService.Entities.ProgressReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsImmutable")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("MediaUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PhysicalPercentage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MilestoneId");

                    b.ToTable("ProgressReports");
                });

            modelBuilder.Entity("ExecutionService.Entities.Query", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("ExecutionService.Entities.QueryMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("QueryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.ToTable("QueryMessage");
                });

            modelBuilder.Entity("ExecutionService.Entities.MilestoneDocument", b =>
                {
                    b.HasOne("ExecutionService.Entities.MilestoneSubmission", "MilestoneSubmission")
                        .WithMany("Documents")
                        .HasForeignKey("MilestoneSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MilestoneSubmission");
                });

            modelBuilder.Entity("ExecutionService.Entities.MilestoneSubmission", b =>
                {
                    b.HasOne("ExecutionService.Entities.Milestone", "Milestone")
                        .WithMany("Submissions")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("ExecutionService.Entities.MilestoneTemplateItem", b =>
                {
                    b.HasOne("ExecutionService.Entities.MilestoneTemplate", "MilestoneTemplate")
                        .WithMany("Items")
                        .HasForeignKey("MilestoneTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MilestoneTemplate");
                });

            modelBuilder.Entity("ExecutionService.Entities.ProgressReport", b =>
                {
                    b.HasOne("ExecutionService.Entities.Milestone", "Milestone")
                        .WithMany()
                        .HasForeignKey("MilestoneId");

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("ExecutionService.Entities.QueryMessage", b =>
                {
                    b.HasOne("ExecutionService.Entities.Query", null)
                        .WithMany("Messages")
                        .HasForeignKey("QueryId");
                });

            modelBuilder.Entity("ExecutionService.Entities.Milestone", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("ExecutionService.Entities.MilestoneSubmission", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ExecutionService.Entities.MilestoneTemplate", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ExecutionService.Entities.Query", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
