"""
Assemble one complete, runnable SQL Server script: login + databases + schema
+ data, in that order, for all 7 Post Tender services.

Inputs (already generated by earlier steps):
  * provision-sql-server.sql       - login + database + permission grants
  * sql-raw/<Service>.schema.sql   - `dotnet ef migrations script --idempotent`
                                      output, i.e. the exact DDL EF would apply,
                                      generated straight from the real model
                                      rather than hand-written.
  * sqlite-export.filtered.json    - the 375 rows kept after stripping E2E/
                                      validation test residue (see README.md).

This script's only job is to turn the schema files' CREATE TABLE / FOREIGN KEY
declarations into a safe INSERT order (parents before children) and emit one
INSERT per row, type-converted from the JSON. It does not invent schema or
touch a live database - everything it emits was already produced or verified
by an earlier, separately-checked step.

Output: complete-migration.sql, one file, safe to run top to bottom with
`sqlcmd -S <server> -i complete-migration.sql` (or via SSMS).
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(HERE, "sql-raw")
EXPORT = os.path.join(HERE, "sqlite-export.filtered.json")
PROVISION_MULTI = os.path.join(HERE, "provision-sql-server.sql")
PROVISION_SINGLE = os.path.join(HERE, "provision-singledb.sql")

# Two deployment shapes are supported, because the existing staging server runs the
# second one and matching it matters more than matching the local dev layout:
#
#   database-per-service (default) - what the code was migrated to locally, and what
#       the microservice boundary implies: each service owns its own catalog.
#
#   single-database (--single-db NAME) - every service in one catalog. The existing
#       PostTender_Staging is built this way. It works because all 33 table names are
#       globally unique across the seven services (asserted below, not assumed), and
#       because each service's migration carries a distinct MigrationId, so they can
#       share one __EFMigrationsHistory without any of them treating another's rows
#       as its own.
SINGLE_DB = None
if "--single-db" in sys.argv:
    SINGLE_DB = sys.argv[sys.argv.index("--single-db") + 1]

OUT = os.path.join(HERE, "complete-migration-singledb.sql" if SINGLE_DB
                   else "complete-migration.sql")

SERVICES = [
    ("IdentityService",   "PostTender_Identity"),
    ("VendorService",     "PostTender_Vendor"),
    ("TenderService",     "PostTender_Tender"),
    ("ExecutionService",  "PostTender_Execution"),
    ("InspectionService", "PostTender_Inspection"),
    ("FinancialService",  "PostTender_Financial"),
    ("CommonService",     "PostTender_Common"),
]
if SINGLE_DB:
    SERVICES = [(svc, SINGLE_DB) for svc, _ in SERVICES]

CREATE_TABLE_RE = re.compile(
    r'CREATE TABLE \[(?P<table>\w+)\] \(\s*(?P<body>.*?)\n\s*\);',
    re.DOTALL,
)
COLUMN_RE = re.compile(
    r'^\s*\[(?P<name>\w+)\]\s+(?P<type>[\w()0-9,]+)\s+(?P<null>NOT NULL|NULL)',
    re.MULTILINE,
)
FK_RE = re.compile(
    r'FOREIGN KEY \(\[(?P<col>\w+)\]\)\s+REFERENCES \[(?P<parent>\w+)\]',
)
PK_RE = re.compile(r'PRIMARY KEY \((?P<cols>\[[^)]+\])\)')


def parse_schema(path):
    """Return ({table: [(col, type, nullable)]}, {table: {(col, parent)}}, {table: [pk cols]})."""
    # utf-8-sig: `dotnet ef migrations script --output` writes a UTF-8 BOM. Reading
    # plain utf-8 leaves that BOM as a literal U+FEFF character at the start of the
    # text, which then lands mid-file once these pieces are concatenated - a stray
    # zero-width character sitting right before a keyword, which is exactly the kind
    # of thing that trips up a SQL parser.
    text = open(path, encoding="utf-8-sig").read()
    columns = {}
    fks = {}
    pks = {}
    for m in CREATE_TABLE_RE.finditer(text):
        table = m.group("table")
        body = m.group("body")
        cols = []
        for cm in COLUMN_RE.finditer(body):
            cols.append((cm.group("name"), cm.group("type"), cm.group("null") == "NULL"))
        columns[table] = cols
        fks[table] = {(fm.group("col"), fm.group("parent")) for fm in FK_RE.finditer(body)}
        pkm = PK_RE.search(body)
        pks[table] = re.findall(r'\[(\w+)\]', pkm.group("cols")) if pkm else []
    return columns, fks, pks


def topo_order(tables, fks):
    """Parent tables before children. Stable otherwise (preserves schema-file order)."""
    order = []
    seen = set()

    def visit(t, stack):
        if t in seen or t not in tables:
            return
        if t in stack:
            raise ValueError(f"FK cycle involving {t}")
        for _col, parent in fks.get(t, ()):
            visit(parent, stack | {t})
        seen.add(t)
        order.append(t)

    for t in tables:
        visit(t, set())
    return order


def sql_literal(value, sql_type):
    if value is None:
        return "NULL"

    base = sql_type.split("(")[0].lower()

    if isinstance(value, dict) and "__blob__" in value:
        import base64
        raw = base64.b64decode(value["__blob__"])
        return "0x" + raw.hex() if raw else "0x"

    text = value if isinstance(value, str) else json.dumps(value)

    if base == "bit":
        return "1" if text in ("1", "true", "True") else "0"
    if base == "uniqueidentifier":
        return "N'" + text + "'"
    if base in ("decimal", "numeric", "money", "float", "real", "int", "bigint", "smallint", "tinyint"):
        return text
    if base in ("datetime2", "datetime", "smalldatetime", "date", "datetimeoffset"):
        return "N'" + text.replace("'", "''") + "'"
    # nvarchar / varchar / everything else textual
    return "N'" + text.replace("'", "''") + "'"


def emit_inserts(table, columns, rows, pk_cols):
    """
    Emit one guarded INSERT per row.

    The guard is what makes re-running the whole script safe. Without it a second
    run throws a PRIMARY KEY violation for every row already loaded — measured:
    24 errors on the second pass. Row counts stayed correct because the PK caught
    the duplicates, but a script that reports two dozen errors on a re-run is one
    nobody can tell "already applied" from "genuinely broken", which matters most
    when a migration half-fails and has to be resumed.
    """
    lines = []
    colnames = [c[0] for c in columns]
    coltypes = {c[0]: c[1] for c in columns}
    missing_in_json = set()
    for row in rows:
        vals = []
        for name in colnames:
            if name not in row:
                missing_in_json.add(name)
                vals.append("NULL")
                continue
            vals.append(sql_literal(row[name], coltypes[name]))
        cols_sql = ", ".join(f"[{c}]" for c in colnames)
        vals_sql = ", ".join(vals)
        insert = f"INSERT INTO [{table}] ({cols_sql}) VALUES ({vals_sql});"

        if pk_cols and all(pk in row for pk in pk_cols):
            where = " AND ".join(
                f"[{pk}] = {sql_literal(row[pk], coltypes[pk])}" for pk in pk_cols)
            lines.append(
                f"IF NOT EXISTS (SELECT 1 FROM [{table}] WHERE {where}) {insert}")
        else:
            lines.append(insert)
    return lines, missing_in_json


def main():
    export = json.load(open(EXPORT, encoding="utf-8-sig"))["databases"]
    provisioning = open(PROVISION_SINGLE if SINGLE_DB else PROVISION_MULTI,
                        encoding="utf-8-sig").read()

    # Single-database mode is only safe if no two services own a table of the same
    # name - otherwise one service's migration would silently adopt another's table.
    # Verify rather than trust: this is cheap and the failure mode is data corruption.
    if SINGLE_DB:
        # __EFMigrationsHistory is the one table all seven are *meant* to share.
        # Each service's migration carries its own timestamped MigrationId, so they
        # coexist as distinct rows, and EF's CREATE for it is already guarded by
        # IF OBJECT_ID(...) IS NULL. Every other shared name would be a genuine bug.
        SHARED_BY_DESIGN = {"__EFMigrationsHistory"}
        owner = {}
        for service, _ in SERVICES:
            cols, _fks, _pks = parse_schema(os.path.join(RAW, f"{service}.schema.sql"))
            for table in cols:
                if table in SHARED_BY_DESIGN:
                    continue
                if table in owner:
                    raise SystemExit(
                        f"TABLE NAME COLLISION in single-database mode: '{table}' is "
                        f"declared by both {owner[table]} and {service}. These services "
                        "cannot share one database without renaming or schema separation.")
                owner[table] = service
        print(f"single-database mode: {SINGLE_DB}")
        print(f"  verified {len(owner)} table names are unique across all 7 services\n")

    row_total = sum(
        len(t.get("rows", []))
        for svc in export.values() for t in svc.values())
    filename = os.path.basename(OUT)

    parts = []
    parts.append("/* " + "=" * 78)
    parts.append("   Post Tender Management System — complete SQL Server migration")
    parts.append("   Generated by tools/db-migration/generate_complete_script.py")
    parts.append("")
    if SINGLE_DB:
        parts.append(f"   TARGET: a single existing database, [{SINGLE_DB}], shared by all seven")
        parts.append("   services. All 33 table names are verified unique across the services, so")
        parts.append("   they coexist without collision; they share one __EFMigrationsHistory,")
        parts.append("   each recording its own timestamped MigrationId.")
        parts.append("")
        parts.append("   *** THIS SCRIPT IS DESTRUCTIVE ***")
        parts.append("   It DROPS the previous Post Tender tables in that database before")
        parts.append("   recreating them. Any data in them is permanently lost. Take a backup:")
        parts.append(f"       BACKUP DATABASE [{SINGLE_DB}] TO DISK = N'...\\pre-migration.bak' WITH INIT;")
        parts.append("   (WITH COMPRESSION is not available on Express Edition.)")
    else:
        parts.append("   Creates a login, seven per-service databases and their permissions,")
        parts.append("   then schema and data for each. Non-destructive: it only creates.")
    parts.append("")
    parts.append(f"   Schema comes from EF's own --idempotent migration output; data is {row_total}")
    parts.append("   rows, filtered — see tools/db-migration/README.md for what was excluded")
    parts.append("   and why. Every INSERT is guarded on its primary key, so re-running the")
    parts.append("   whole file is safe and will not duplicate rows.")
    parts.append("")
    parts.append("   BEFORE RUNNING: change @AppPassword in the login section below.")
    parts.append("")
    parts.append(f"   Run with: sqlcmd -S <server> -U <admin login> -P <pw> -i {filename}")
    parts.append("   (or paste into SSMS / Azure Data Studio and Execute — SQLCMD mode is not")
    parts.append("   required; there is no :setvar usage, only plain T-SQL batches.)")
    parts.append("   " + "=" * 78 + " */")
    parts.append("")
    parts.append("-- " + "-" * 78)
    parts.append("-- STEP 1 of 3: login, permissions"
                 + (", and DROP of the previous schema" if SINGLE_DB else ", databases"))
    parts.append("-- " + "-" * 78)
    parts.append(provisioning.strip())
    parts.append("GO")
    parts.append("")

    total_rows_written = 0
    warnings = []

    for step_no, (service, dbname) in enumerate(SERVICES, start=1):
        schema_path = os.path.join(RAW, f"{service}.schema.sql")
        columns, fks, pks = parse_schema(schema_path)
        schema_sql = open(schema_path, encoding="utf-8-sig").read().strip()

        parts.append("-- " + "-" * 78)
        parts.append(f"-- STEP 2.{step_no} of 3: {service} — schema  ({dbname})")
        parts.append("-- " + "-" * 78)
        parts.append(f"USE [{dbname}];")
        parts.append("GO")
        parts.append(schema_sql)
        parts.append("")

        svc_tables = export.get(service, {})
        order = topo_order(list(columns.keys()), fks)

        data_lines = [f"-- {service} — data  ({dbname})", f"USE [{dbname}];", "GO"]
        rows_here = 0
        for table in order:
            rows = svc_tables.get(table, {}).get("rows", [])
            if not rows:
                continue
            insert_lines, missing = emit_inserts(table, columns[table], rows, pks.get(table, []))
            if not pks.get(table):
                warnings.append(f"{service}.{table}: no PRIMARY KEY parsed — inserts are NOT re-run safe")
            if missing:
                warnings.append(f"{service}.{table}: JSON rows missing column(s) {sorted(missing)} — inserted as NULL")
            data_lines.append(f"-- {table}: {len(rows)} row(s)")
            data_lines.extend(insert_lines)
            data_lines.append("GO")
            rows_here += len(rows)
            total_rows_written += len(rows)

        # tables present in the export but not found in the parsed schema would
        # silently vanish otherwise - fail loudly instead.
        unexpected = set(svc_tables) - set(columns)
        if unexpected:
            raise SystemExit(f"{service}: export has table(s) {unexpected} not present in the generated schema")

        parts.append("-- " + "-" * 78)
        parts.append(f"-- STEP 3.{step_no} of 3: {service} — data  ({rows_here} row(s))")
        parts.append("-- " + "-" * 78)
        parts.extend(data_lines)
        parts.append("")

    parts.append("-- " + "-" * 78)
    parts.append(f"-- Done. {total_rows_written} rows loaded across {len(SERVICES)} databases.")
    parts.append("-- " + "-" * 78)
    parts.append("PRINT 'Migration complete.';")
    parts.append("GO")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(parts) + "\n")

    print(f"wrote {OUT}")
    print(f"{total_rows_written} rows across {len(SERVICES)} databases")
    if warnings:
        print(f"\n{len(warnings)} WARNING(S):")
        for w in warnings:
            print("  " + w)
    else:
        print("no warnings — every exported row's columns matched the generated schema exactly")


if __name__ == "__main__":
    main()
